name: "RSpec Tests and Simplecov coverage"
on:
  pull_request:
    branches: [ "main" ]

env:
  RAILS_ENV: test
  DATABASE_URL: "postgres://user:password@localhost:5432/municipe_test"
  REDIS_URL: "redis://redis:6379/0"
  ELASTICSEARCH_URL: 'http://localhost:9200'

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: municipe_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
      elasticsearch:
        image: elasticsearch:6.8.3
        ports: ["9200:9200"]
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      redis:
        image: redis
        ports: ["6379:6379"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: |
          bin/rails db:drop
          bin/rails db:create
          bin/rails db:migrate

      - name: Verify Elasticsearch connection from host
        env:
          ELASTICSEARCH_URL: 'http://localhost:9200'
        run: |
          echo $ELASTICSEARCH_URL
          curl -fsSL "$ELASTICSEARCH_URL/_cat/health?h=status"

      - name: Run RSpec tests
        run: bundle exec rspec
